### PR TITLE
chore: update angular demo and add ts-patch script

### PR DESCRIPTION
**Pull request by rickwalking**

### CODE REVIEW

**Review by bradmartin — COMMENTED** [review]
Nice PR, some minor changes can be made but this will def get NS7 running. I plan to make a few more changes to the entire repo if @manijak will approve so we can have NS7 support published soon.

**Comment by rickwalking** [comment]
@bradmartin Are you planning on updating it to the new workspace that just came out?

**Comment by bradmartin** [comment]
Would love to but that would be with @manijak blessing as this is his repo and project. I don't want to hijack it just for simplifying it into the plugins workspace :)

So I was just going to take master after your merge and get everything on the latest here for Ned to publish a major version for NS7 👍

**Comment by manijak** [comment]
Thanks a bunch to both of you. Since I've been preoccupied with staying awake & changing diapers for the past month or so, I haven't been following the NS news lately :)  So all this "new plugin workspace" talk was a big unknown to me :D 

But yeah, until I get my senses back, you have my blessing to do all the work needed to get the plugins working 👍

**Comment by bradmartin** [comment]
@manijak - this is the plugins workspace https://github.com/NativeScript/plugins it's a mono repo for plugins basically but they're scoped under @nativescript. It's intended to make managing multiple plugins much easier to update. Instead of having multiple repos where you go update deps and the code, you have one place for the deps. So when new TS comes out, you update once, run the plugins and boom can publish and automate a bunch of stuff along the way.

However, not everyone will need to do that or want to. You can keep yours here and I'm about to update it to the latest NS7 support 👍

**Pull request merged**
