### PR TITLE
Feat: NS7 overhaul

### PR DESCRIPTION
**Pull request by bradmartin**

### CODE REVIEW

**Comment by bradmartin** [comment]
@manijak  - large PR was hard to avoid but the plain demo app is working on the latest NS confirmed both iOS and Android. I'm running the ng demo now to confirm it's working as expected.

**Comment by bradmartin** [comment]
Working tgz for now until published. 

[nativescript-carousel-7.0.1.tgz.zip](https://github.com/manijak/nativescript-carousel/files/5227155/nativescript-carousel-7.0.1.tgz.zip)

**Comment by bradmartin** [comment]
Ng-demo also running as expected ❤️  so we should be good to publish this out as a major bump. Looks like the package.json was already bumped in a previous PR for `7.0.1` so that should be fine or `7.0.0` if it's not been published.

**Comment by manijak** [comment]
Roger that, thanks for the PR 😃

**Comment by Klunk75** [comment]
Hi,
first of all thanks a lot to all contributors for this NS7 update!
Unfortunately i get this error trying to run ng-demo on Android platform:

System.err: An uncaught Exception occurred on "main" thread.
System.err: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function
System.err: ReferenceError: NativeClass is not defined
System.err: File: (file: node_modules\nativescript-carousel\carousel.android.js:294:0)

Anybody else facing this issue?
Thanks, Paolo

---
NS 7.0.8 & all packages updated to latest version.

**Comment by bradmartin** [comment]
@Klunk75 - your project shouldn't be analyzing node_modules so be sure if you're using TS to have the `skipLibCheck` set to `false` in your tsconfig. 

At any rate, I'm going to pull the master and run the demo and see if I can reproduce if not, then also check your CLI version to be sure you're on NS7 with `ns info` and then try rebuilding. I do believe I confirmed the android angular demo to be working but I'll double check.

**Comment by bradmartin** [comment]
```
The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
MacBook-Pro:nativescript-carousel bradmartin$ cd src
MacBook-Pro:src bradmartin$ npm run build

> nativescript-carousel@7.0.0 build /Users/bradmartin/Desktop/nativescript-carousel/src
> npm i && ts-patch install && npm run tsc.dist

npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.

> fsevents@1.2.13 install /Users/bradmartin/Desktop/nativescript-carousel/src/node_modules/watchpack-chokidar2/node_modules/fsevents
> node install.js

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node

> husky@4.3.0 install /Users/bradmartin/Desktop/nativescript-carousel/src/node_modules/husky
> node husky install

husky > Setting up git hooks
husky > Done

> ejs@2.7.4 postinstall /Users/bradmartin/Desktop/nativescript-carousel/src/node_modules/ejs
> node ./postinstall.js

Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)


> @nativescript/core@7.0.3 postinstall /Users/bradmartin/Desktop/nativescript-carousel/src/node_modules/@nativescript/core
> node cli-hooks/postinstall.js


> @nativescript/webpack@3.0.4 postinstall /Users/bradmartin/Desktop/nativescript-carousel/src/node_modules/@nativescript/webpack
> node postinstall.js

Skipping postinstall artifacts! We assumed the @nativescript/webpack is installing devDependencies

> husky@4.3.0 postinstall /Users/bradmartin/Desktop/nativescript-carousel/src/node_modules/husky
> opencollective-postinstall || exit 0

Thank you for using husky!
If you rely on this package, please consider supporting our open collective:
> https://opencollective.com/husky/donate

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN notsup Unsupported engine for watchpack-chokidar2@2.0.0: wanted: {"node":"<8.10.0"} (current: {"node":"12.14.1","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: watchpack-chokidar2@2.0.0

added 838 packages from 445 contributors and audited 840 packages in 32.168s

38 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

[+] ts-patch installed!

> nativescript-carousel@7.0.0 tsc.dist /Users/bradmartin/Desktop/nativescript-carousel/src
> npm run dist.clean && tsc -skipLibCheck --outDir dist && npm run dist.copy


> nativescript-carousel@7.0.0 dist.clean /Users/bradmartin/Desktop/nativescript-carousel/src
> rimraf dist


> nativescript-carousel@7.0.0 dist.copy /Users/bradmartin/Desktop/nativescript-carousel/src
> cp -R platforms dist && cp ../README.md dist && cp carousel.d.ts dist && cp package.json dist

MacBook-Pro:src bradmartin$ npm run demo-ng.android

> nativescript-carousel@7.0.0 demo-ng.android /Users/bradmartin/Desktop/nativescript-carousel/src
> cd ../demo-ng && tns run android

Searching for devices...
Starting Android emulator with image Pixel_3a_API_29
Waiting for emulator device initialization...
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.

> fsevents@1.2.13 install /Users/bradmartin/Desktop/nativescript-carousel/demo-ng/node_modules/watchpack-chokidar2/node_modules/fsevents
> node install.js

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node

> core-js@2.6.11 postinstall /Users/bradmartin/Desktop/nativescript-carousel/demo-ng/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> ejs@2.7.4 postinstall /Users/bradmartin/Desktop/nativescript-carousel/demo-ng/node_modules/ejs
> node ./postinstall.js

Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)


> @nativescript/core@7.0.0 postinstall /Users/bradmartin/Desktop/nativescript-carousel/demo-ng/node_modules/@nativescript/core
> node cli-hooks/postinstall.js


> @nativescript/webpack@3.0.0 postinstall /Users/bradmartin/Desktop/nativescript-carousel/demo-ng/node_modules/@nativescript/webpack
> node postinstall.js

Dev dependency: @angular/compiler-cli already added. Leaving version: 10.1.1
Dev dependency: @ngtools/webpack already added. Leaving version: 10.1.1
Some dependencies have already been added. If you want to force update them, please run "node_modules/.bin/update-ns-webpack".


> demo-angular-carousel@1.0.0 postinstall /Users/bradmartin/Desktop/nativescript-carousel/demo-ng
> ngcc --properties es2015 module main --first-only

Compiling @angular/core : es2015 as esm2015
Compiling @angular/animations : es2015 as esm2015
Compiling @angular/compiler/testing : es2015 as esm2015
Compiling @angular/common : es2015 as esm2015
Compiling @angular/animations/browser : es2015 as esm2015
Compiling @angular/core/testing : es2015 as esm2015
Compiling @angular/platform-browser : es2015 as esm2015
Compiling @angular/common/http : es2015 as esm2015
Compiling @angular/router : es2015 as esm2015
Compiling @angular/forms : es2015 as esm2015
Compiling @angular/common/testing : es2015 as esm2015
Compiling @angular/animations/browser/testing : es2015 as esm2015
Compiling @angular/platform-browser/animations : es2015 as esm2015
Compiling @angular/platform-browser-dynamic : es2015 as esm2015
Compiling @angular/platform-browser/testing : es2015 as esm2015
Compiling @angular/common/http/testing : es2015 as esm2015
Compiling @angular/router/testing : es2015 as esm2015
Compiling @angular/platform-browser-dynamic/testing : es2015 as esm2015
Compiling @nativescript/angular : es2015 as esm2015
Compiling @nativescript/angular/testing : es2015 as esm2015
Compiling nativescript-angular : es2015 as esm2015
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN notsup Unsupported engine for watchpack-chokidar2@2.0.0: wanted: {"node":"<8.10.0"} (current: {"node":"12.14.1","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: watchpack-chokidar2@2.0.0
npm WARN @angular/core@10.1.2 requires a peer of zone.js@~0.10.3 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/compiler-cli@10.1.1 requires a peer of @angular/compiler@10.1.1 but none is installed. You must install peer dependencies yourself.
npm WARN demo-angular-carousel@1.0.0 No repository field.

added 759 packages from 418 contributors and audited 761 packages in 45.04s

28 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

Copying template files...
⠇ ⸨░░░░░░░░░░░░░░░░░░⸩ ⠇ rollbackFailedOptional: WARN install Usage of the `--dev` option is deprecated. Use `--only=⠏ ⸨░░░░░░░░░░░░░░░░░░⸩ ⠇ rollbackFailedOptional: WARN install Usage of the `--dev` option is deprecated. Use `--only=⠙ ⸨░░░░░░░░░░░░░░░░░░⸩ ⠇ rollbackFailedOptional: WARN install Usage of the `--dev` option is deprecated. Use `--only=⠸ ⸨░░░░░░░░░░░░░░░░░░⸩ ⠇ rollbackFailedOptional: WARN install Usage of the `--dev` option is deprecated. Use `--only=⠼ ⸨░░░░░░░░░░░░░░░░░░⸩ ⠇ rollbackFailedOptional: WARN install Usage of the `--dev` option is deprecated. Use `--only=⠴ ⸨░░░░░░░░░░░░░░░░░░⸩ ⠇ rollbackFailedOptional: WARN install Usage of the `--dev` option is deprecated. Use `--only=⠦ ⸨░░░░░░░░░░░░░░░░░░⸩ ⠇ rollbackFailedOptional: WARN install Usage of the `--dev` option is deprecated. Use `--only=⠦ ⸨   ░░░░░░░░░░░░░░░⸩ ⠏ loadDep:source-map: sill removeObsoleteDep removing @nativescript/android@7.0.0 from the tre⠇ ⸨       ░░░░░░░░░░░⸩ ⠴ extract:@nativescript/android: verb lock using /Users/bradmartin/.npm/_locks/staging-fa03300⠏ ⸨       ░░░░░░░░░░░⸩ ⠴ extract:@nativescript/android: verb lock using /Users/bradmartin/.npm/_locks/staging-fa03300⠋ ⸨       ░░░░░░░░░░░⸩ ⠴ extract:@nativescript/android: verb lock using /Users/bradmartin/.npm/_locks/staging-fa03300⠙ ⸨       ░░░░░░░░░░░⸩ ⠴ extract:@nativescript/android: verb lock using /Users/bradmartin/.npm/_locks/staging-fa03300⠹ ⸨       ░░░░░░░░░░░⸩ ⠴ extract:@nativescript/android: verb lock using /Users/bradmartin/.npm/_locks/staging-fa03300⠸ ⸨       ░░░░░░░░░░░⸩ ⠇ extract:@nativescript/android: verb lock using /Users/bradmartin/.npm/_locks/staging-fa03300⠼ ⸨       ░░░░░░░░░░░⸩ ⠇ extract:@nativescript/android: verb lock using /Users/bradmartin/.npm/_locks/staging-fa03300⠴ ⸨       ░░░░░░░░░░░⸩ ⠇ extract:@nativescript/android: verb lock using /Users/bradmartin/.npm/_locks/staging-fa03300⠦ ⸨       ░░░░░░░░░░░⸩ ⠇ extract:@nativescript/android: verb lock using /Users/bradmartin/.npm/_locks/staging-fa03300⠋ ⸨            ░░░░░░⸩ ⠹ postinstall: info lifecycle @nativescript/android@7.0.0~postinstall: @nativescript/android@7+ @nativescript/android@7.0.0
updated 1 package and audited 761 packages in 3.545s
⠸ 
28 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

Platform android successfully added. v7.0.0
Preparing project...
File change detected. Starting incremental webpack compilation...

webpack is watching the files…

Hash: ade5739c38e97fdf9b08
Version: webpack 4.44.1
Time: 7473ms
Built at: 09/17/2020 12:22:53 AM
              Asset      Size   Chunks             Chunk Names
      assets/01.jpg   118 KiB           [emitted]  
      assets/02.jpg   121 KiB           [emitted]  
      assets/03.jpg  92.8 KiB           [emitted]  
      assets/04.jpg   142 KiB           [emitted]  
 assets/ng-logo.png  1.79 KiB           [emitted]  
          bundle.js   146 KiB   bundle  [emitted]  bundle
       package.json  1.26 KiB           [emitted]  
         runtime.js  77.1 KiB  runtime  [emitted]  runtime
tns-java-classes.js   0 bytes           [emitted]  
          vendor.js  16.7 MiB   vendor  [emitted]  vendor
Entrypoint bundle = runtime.js vendor.js bundle.js
[../$$_lazy_route_resource lazy recursive] ../$$_lazy_route_resource lazy namespace object 160 bytes {bundle} [built]
[../../src/dist/carousel.common.js] /Users/bradmartin/Desktop/nativescript-carousel/src/dist/carousel.common.js 7.19 KiB {bundle} [built]
[../../src/dist/carousel.js] /Users/bradmartin/Desktop/nativescript-carousel/src/dist/carousel.js 13.9 KiB {bundle} [built]
[./app.component.ts] 1.08 KiB {bundle} [built]
[./app.css] 1.3 KiB {bundle} [built]
[./app.module.ts] 2.17 KiB {bundle} [built]
[./app.routing.ts] 1.56 KiB {bundle} [built]
[./item/carousel-advanced.component.ts] 6.43 KiB {bundle} [built]
[./item/carousel-dynamic.component.ts] 5.79 KiB {bundle} [built]
[./item/carousel-static.component.ts] 4.26 KiB {bundle} [built]
[./item/item.service.ts] 920 bytes {bundle} [built]
[./item/items.component.ts] 2.02 KiB {bundle} [built]
[./main.ts] 2.29 KiB {bundle} [built]
[~/package.json] external "~/package.json" 42 bytes {bundle} [optional] [built]
    + 546 hidden modules

WARNING in /Users/bradmartin/Desktop/nativescript-carousel/demo-ng/nativescript.config.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.
Webpack compilation complete. Watching for file changes.
Webpack build done!
Updating runtime package.json with configuration values...
Project successfully prepared (android)
Building project...
Gradle build...
         + setting applicationId
         + applying user-defined configuration from /Users/bradmartin/Desktop/nativescript-carousel/demo-ng/App_Resources/Android/app.gradle
         + using android X library androidx.legacy:legacy-support-v4:1.0.0
         + adding nativescript runtime package dependency: nativescript-optimized-with-inspector
         + adding aar plugin dependency: /Users/bradmartin/Desktop/nativescript-carousel/demo-ng/node_modules/@nativescript/core/platforms/android/widgets-release.aar
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Project successfully built.
The build result is located at: /Users/bradmartin/Desktop/nativescript-carousel/demo-ng/platforms/android/app/build/outputs/apk/debug/app-debug.apk
Installing on device emulator-5554...
Successfully installed on device with identifier 'emulator-5554'.
Restarting application on device emulator-5554...
Successfully synced application org.nativescript.demongcarousel on device emulator-5554.
JS: HMR: Hot Module Replacement Enabled. Waiting for signal.
JS: Angular is running in development mode. Call enableProdMode() to enable production mode.
JS: NativeScript-Carousel DEBUG:  createNativeView
JS: ---------------------------------------------------
JS: NativeScript-Carousel DEBUG:  initNativeView
JS: ---------------------------------------------------
JS: NativeScript-Carousel DEBUG:  refresh()
JS: ---------------------------------------------------
JS: NativeScript-Carousel DEBUG:  Items count:  4
JS: ---------------------------------------------------
JS: NativeScript-Carousel DEBUG:  setOffscreenPageLimit
JS: ---------------------------------------------------
JS: NativeScript-Carousel DEBUG:  this.nativeView = androidx.viewpager.widget.ViewPager{4df68c3 VFED..... ......I. 0,0-0,0 #2}
JS: ---------------------------------------------------
JS: NativeScript-Carousel DEBUG:  indicatorColorProperty.setNative value = #FFF000
JS: ---------------------------------------------------
JS: NativeScript-Carousel DEBUG:  indicatorAnimationProperty.setNative value = WORM
JS: ---------------------------------------------------
JS: NativeScript-Carousel DEBUG:  onLoaded
JS: ---------------------------------------------------
JS: NativeScript-Carousel DEBUG:  createNativeView
JS: ---------------------------------------------------
JS: NativeScript-Carousel DEBUG:  initNativeView
JS: ---------------------------------------------------
JS: NativeScript-Carousel DEBUG:  refresh()
JS: ---------------------------------------------------
JS: NativeScript-Carousel DEBUG:  Items count:  4
JS: ---------------------------------------------------
JS: NativeScript-Carousel DEBUG:  setOffscreenPageLimit
JS: ---------------------------------------------------
JS: NativeScript-Carousel DEBUG:  this.nativeView = androidx.viewpager.widget.ViewPager{92f6a92 VFED..... ......I. 0,0-0,0 #2}
JS: ---------------------------------------------------
JS: NativeScript-Carousel DEBUG:  indicatorColorProperty.setNative value = #FFF000
JS: ---------------------------------------------------
JS: NativeScript-Carousel DEBUG:  indicatorAnimationProperty.setNative value = WORM
JS: ---------------------------------------------------
JS: NativeScript-Carousel DEBUG:  onLoaded
JS: ---------------------------------------------------
JS: NativeScript-Carousel DEBUG:  -------> CarouselPagerAdapter instantiateItem() 0
JS: ---------------------------------------------------
JS: NativeScript-Carousel DEBUG:  -------> PagerAdapter: Collection count:  4
JS: ---------------------------------------------------
JS: NativeScript-Carousel DEBUG:  -------> PagerAdapter: Carousel count:  4
JS: ---------------------------------------------------
JS: NativeScript-Carousel DEBUG:  -------> PagerAdapter: Items count:  4
JS: ---------------------------------------------------
JS: NativeScript-Carousel DEBUG:  -------> CarouselPagerAdapter instantiateItem() 1
JS: ---------------------------------------------------
JS: NativeScript-Carousel DEBUG:  -------> PagerAdapter: Collection count:  4
JS: ---------------------------------------------------
JS: NativeScript-Carousel DEBUG:  -------> PagerAdapter: Carousel count:  4
JS: ---------------------------------------------------
JS: NativeScript-Carousel DEBUG:  -------> PagerAdapter: Items count:  4
JS: ---------------------------------------------------
JS: NativeScript-Carousel DEBUG:  -------> CarouselPagerAdapter instantiateItem() 2
JS: ---------------------------------------------------
JS: NativeScript-Carousel DEBUG:  -------> PagerAdapter: Collection count:  4
JS: ---------------------------------------------------
JS: NativeScript-Carousel DEBUG:  -------> PagerAdapter: Carousel count:  4
JS: ---------------------------------------------------
JS: NativeScript-Carousel DEBUG:  -------> PagerAdapter: Items count:  4
JS: ---------------------------------------------------
JS: NativeScript-Carousel DEBUG:  -------> CarouselPagerAdapter instantiateItem() 3
JS: ---------------------------------------------------
JS: NativeScript-Carousel DEBUG:  -------> PagerAdapter: Collection count:  4
JS: ---------------------------------------------------
JS: NativeScript-Carousel DEBUG:  -------> PagerAdapter: Carousel count:  4
JS: ---------------------------------------------------
JS: NativeScript-Carousel DEBUG:  -------> PagerAdapter: Items count:  4
JS: ---------------------------------------------------
JS: NativeScript-Carousel DEBUG:  CarouselPagerAdapterClassInner saveState()
JS: ---------------------------------------------------
```

**Comment by bradmartin** [comment]
hey @manijak - the 7.0.0 publish is bad. I guess I should have clarified depending how you normally publish :)

So if you look at the scripts in the package.json you'll see a `ts-patch install` in the `build` script. That needs to be run to handle the @NativeClass() decorator which allows that specific class/block of code to be transpiled to ES5 bc it's extending native code and the runtimes only work with JS at ES5 for the `extends` calls. The code outside of the `NativeClass()` works with ES2017 now all across the board. Those extended native classes are only thing that have to be ES5 JS.

**Comment by manijak** [comment]
Yeah, I just used what I always used: the `build.sh` script in the `publish` folder 😃 . But this only runs `tsc`, and copies other essential files from `src`. So I guess I'm missing the `ts-patch install` part.

**Comment by manijak** [comment]
Published 7.0.1 with a potential fix

**Comment by bradmartin** [comment]
Nice and thanks @manijak - it's perfect.
money

If you look at the JS source. The plain TS class is still ES2017 👍  and the extended native class is transpiled down to ES5 due to the current runtime support of the `extends` processes. So this will work perfectly.

**Comment by Klunk75** [comment]
> @Klunk75 - your project shouldn't be analyzing node_modules so be sure if you're using TS to have the `skipLibCheck` set to `false` in your tsconfig.
> 
> At any rate, I'm going to pull the master and run the demo and see if I can reproduce if not, then also check your CLI version to be sure you're on NS7 with `ns info` and then try rebuilding. I do believe I confirmed the android angular demo to be working but I'll double check.

@bradmartin, thank you for your directions.
I think you meant to set 'skipLibCheck' to true, not to false (by default in the demo it's already set to true).
Anyway, with version 7.0.1 the issue is fixed, all seems to work perfectly now.
Thanks again to you and @manijak for the great work!

Paolo

**Comment by bradmartin** [comment]
Yeah 😆 `true` 🤦 , but you got it. Glad this plugin is rocking again 🎉  thanks for finding that issue @Klunk75

**Pull request merged**
