### PR TITLE
chore: update to latest deps

### PR DESCRIPTION
**Pull request by NathanWalker**
In preparation of {N} 7.0, this helps prepare this plugin for latest. No need to bump and publish just yet until we make the final release as you'll see this is using the current core rc 👍

### CODE REVIEW

**Comment by manijak** [comment]
Roger that. Thanks 👍

**Comment by Klunk75** [comment]
Hi,
it would be nice Nathan commits would be merged, in order to use this plugin with {N} RC + ANGULAR 10.
Thanks!

Paolo

**Comment by rickwalking** [comment]
Would be nice if it is merged.

**Comment by manijak** [comment]
Sorry for the afk, been busy with a new family member and all :) 
On top of everything my MacBook decided to die on me, so as soon as I get it back from service, I'll see to this.

**Pull request merged**
